[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
arch = "arm64-v8a"
build-mode = "module"
included-patches = "'Custom branding icon for YouTube' 'MaterialYou'"
excluded-patches = "'GmsCore support'"

