[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea ReVanced"
build-mode = "module"
version = "19.47.53"
included-patches = "'MaterialYou'"
patcher-args = "-e 'Custom branding icon for YouTube' -OappIcon=Revancify Blue"
excluded-patches = "'GmsCore support'"
